{{- if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "llm-apm.labels" . | nindent 4 }}
spec:
  # replicas removed so HPA can control scaling
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
    spec:
      serviceAccountName: backend-sa
      automountServiceAccountToken: false
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "{{ .Values.secretsProvider.name }}"
      containers:
      - name: {{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        envFrom:
        - secretRef:
            name: {{ .Values.backend.envSecretName }}
        volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets-store
          readOnly: true
        readinessProbe:
          httpGet:
            path: {{ .Values.backend.readinessProbe.path }}
            port: {{ .Values.backend.containerPort }}
          initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.readinessProbe.timeoutSeconds }}
        livenessProbe:
          httpGet:
            path: {{ .Values.backend.livenessProbe.path }}
            port: {{ .Values.backend.containerPort }}
          initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.backend.livenessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.backend.containerPort }}
      protocol: TCP
{{- end }}
