{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - name: {{ .Values.redis.name }}
        image: {{ .Values.redis.image }}
        ports:
        - containerPort: {{ .Values.redis.containerPort }}
        resources:
{{ toYaml .Values.redis.resources | indent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.redis.type }}
  selector:
    app: {{ .Values.redis.name }}
  ports:
  - port: {{ .Values.service.redis.port }}
    targetPort: {{ .Values.redis.containerPort }}
    name: redis
{{- end }}
