apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: llm-apm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-secret

      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-keyvault-secrets"

      containers:
        - name: frontend
          image: 1234suhas/llm-apm-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: frontend-env-secret

          volumeMounts:
            - name: secrets-store-inline
              mountPath: /mnt/secrets-store
              readOnly: true

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          command:
            - /bin/sh
            - -c
            - |
              echo ">>> generating /usr/share/nginx/html/env-config.js from pod env..."
              printf '%s\n' "window.__env = {" \
                "  VITE_API_BASE_URL: \"${VITE_API_BASE_URL:-}\"," \
                "  VITE_GRAFANA_URL: \"${VITE_GRAFANA_URL:-}\"" \
                "};" > /usr/share/nginx/html/env-config.js || true

              if [ -f /usr/share/nginx/html/index.html ]; then
                if ! grep -q '/env-config.js' /usr/share/nginx/html/index.html 2>/dev/null; then
                  echo ">>> injecting /env-config.js loader"
                  awk 'BEGIN{inserted=0} /<script[^>]*type=\"module\"[^>]*>/ && !inserted { print \"    <script src=\\\"/env-config.js\\\"></script>\"; inserted=1 } { print } END { if(!inserted) print \"    <script src=\\\"/env-config.js\\\"></script>\" }' /usr/share/nginx/html/index.html > /tmp/index.html.new && mv /tmp/index.html.new /usr/share/nginx/html/index.html || true
                fi
              fi

              echo ">>> starting nginx"
              exec nginx -g 'daemon off;'


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: llm-apm
spec:
  type: LoadBalancer  
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
